spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db_prod
    username: db_prod_user
    password: mydb
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true