INSERT INTO SHOP (name) VALUES ('AmericanShop');
INSERT INTO SHOP (name) VALUES ('FrenchShop');
INSERT INTO SHOP (name) VALUES ('AfricanShop');
INSERT INTO APPORDER (name) VALUES ('ORDER 1');
INSERT INTO APPORDER (name) VALUES ('ORDER 2');
INSERT INTO APPORDER (name) VALUES ('ORDER 3');
